variables:
  GIT_SSL_NO_VERIFY: "true"

image: starefossen/ruby-node:2-6

before_script:
  - ruby -v
  - node -v
  - npm -v
  - gem install bundler
  - bin/setup

cache:
  paths:
    - vendor/bundle
    - node_modules

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - grunt build
  artifacts:
    paths:
    - keepachangelog-*.gem

style:
  script:
    - "grunt test:style"

spec:
  script:
    - "grunt test:spec"

integration:
  script:
    - "grunt test:integration"

fileshare:
  stage: deploy
  environment: production
  script:
    - |
      if [[ "$SSH_KEY" == "" || "$SSH_USER" == "" || "$TARGET_HOST" == "" || "$TARGET_PATH" == "" ]]; then
        echo "Skipping deploy due to missing credentials"
        exit 0
      fi
    - grunt publish
  only:
    - tags

rubygems.org:
  stage: deploy
  environment: production
  script:
    - |
      if [[ "$RUBYGEMS_API_KEY" == "" ]]; then
        echo "Skipping deploy due to missing credentials"
        exit 0
      fi
    - mkdir -p ~/.gem
    - "echo \":rubygems_api_key: $RUBYGEMS_API_KEY\" > ~/.gem/credentials"
    - chmod 0600 /root/.gem/credentials
    - gem build keepachangelog.gemspec
    - gem push keepachangelog-*.gem
  only:
    - tags
